lang: 'de'
runnable: True
#do_mail: False " wenn dies auskommentiert wird, wird der parameter "--mail" ignoriert
#do_twitter: False " wenn dies auskommentiert wird, wird der parameter "--twitter" ignoriert und es wird NICHT getwittert
mail_from: "weeklyteam <{c.mail_user}>"
mail_subject: 'weeklyOSM #{c.post_nr} {c.daterange_str}'
tw_text: "weeklyOSM Ausgabe {c.post_nr} ist nun in *Deutsch* verfügbar. Die neuesten Nachrichten aus der #openstreetmap #osm Welt https://www.weeklyosm.eu/de/archives/{c.url_nr}"
mail_to: 
  - "you could enter emails directly here, but it can/will"
  - "be overwritten by content from mailto/weekly_en.yaml"
mail_body: | 
   Die Wochennotiz Ausgabe Nr. # {c.post_nr}, ist nun verfügbar - 
   wie immer mit vielen Nachrichten aus dem OSM-Universium:
  
   {c.url}
  
   Viel Spaß beim Lesen.  

   Euer Wochennotizteam
   
   Wusstet ihr, dass ihr auch selbst Meldungen für die Wochennotiz
   einreichen könnt? Einfach auf https://osmbc.openstreetmap.de/ 
   mit eurem OSM-Benutzerkonto anmelden und dann den Gastzugang benutzen. 

   weeklyOSM? 
   who: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
   where?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
