lang: 'es' ### overwrite language
runnable: True
#do_mail: False " wenn dieses auskommentiert wird, wird der paramterer "--mail" ignoriert
#do_twitter: False " wenn dieses auskommentiert wird, wird der paramterer "--twitter" ignoriert und NICHT getwittert
mail_subject: 'semanarioOSM Nº {c.post_nr} {c.daterange_str}'
mail_to: 
 - "talk-bo@openstreetmap.org"
 - "talk-latam@openstreetmap.org"
 - "talk-co@openstreetmap.org"
 - "talk-mx@openstreetmap.org"
 - "talk-cl@openstreetmap.org"
 - "talk-cu@openstreetmap.org"
 - "talk-es@openstreetmap.org"
tw_text: "El semanario Nº {c.post_nr} de OSM en *ESPAÑOL* está online, noticias del mundo #openstreetmap #osm - http://www.weeklyosm.eu/es/archives/{c.url_nr}"
mail_body: |
  Hola, el semanario Nº {c.post_nr}, el sumario de todo lo que está ocurriendo en el mundo de openstreetmap está en línea en *español*:

  {c.url}

  ¡Disfruta!

  semanarioOSM? 
  ¿Dónde?: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
  ¿Quién?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
