lang: 'int'
url: "https://www.weeklyosm.eu/en/archives/{c.url_nr}/"
runnable: True
#do_mail: False     # uncomment in order to ignore "--mail" for this language
do_twitter: False   # comment to send an additional tweet in this language if "--twitter" is called (attention: shorten text to <280 chars!)
#do_mastodon: False # uncomment in order to ignore "--mastodon" for this language
do_pin_mastodon: True
do_unpin_mastodon: True

tw_text: "👉 https://www.weeklyosm.eu/archives/{c.url_nr} 👈  Issue {c.post_nr} of weeklyOSM is out. 🌏 涵蓋 #開放街圖 #osm 世界大小事的新一期 weeklyOSM 已經發佈 🚀 Lisez les dernières nouvelles de l'univers #openstreetmap 🗺️ Viele Neuigkeiten aus der #osm Welt 📰 新一期的OSM周刊已经发布 🌏 Se ha publicado un nuevo número del semanarioOSM 🌐 最新の週刊OSMが発行されました。⛩️  주간OSM 최신호가 나왔습니다  💬 Тижневик OSM тепер доступний Українською 📲 👉 https://www.weeklyosm.eu/archives/{c.url_nr} 👈 "

mail_from: "weeklyteam <{c.mail_user}>"
mail_subject: 'weeklyOSM #{c.post_nr} {c.daterange_str}'
mail_body: | 
  The weekly round-up of OSM news, issue # {c.post_nr},
  is now available online, giving as always a summary of a lot of things happening in the openstreetmap world:
  
  https://www.weeklyosm.eu/archives/{c.url_nr}

  Enjoy! 

  Did you know that you can also submit messages for the weeklyOSM? Just log in to https://osmbc.openstreetmap.de/login with your OSM account. Read more about how to write a post here: https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm 

  weeklyOSM? 
  who: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
  where?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
