lang: 'en'
runnable: True
#do_mail: False    # uncomment in order to ignore "--mail" for this language
#do_twitter: False # uncomment in order to ignore "--twitter" for this language
do_mastodon: False # comment to send an additional toot in this language if "--mastodon" is called
mail_from: "weeklyteam <{c.mail_user}>"
mail_subject: 'weeklyOSM #{c.post_nr} {c.daterange_str}'
tw_text: "weeklyOSM issue {c.post_nr}  now available in *English* the news from the #openstreetmap #osm world https://www.weeklyosm.eu/archives/{c.url_nr}"
mail_to: 
  - "you could enter emails directly here, but it can/will"
  - "be overwritten by content from mailto/weekly_en.yaml"
mail_body: | 
  The weekly round-up of OSM news, issue # {c.post_nr},
  is now available online in English, giving as always a summary of a lot of things happening in the openstreetmap world:
  
  https://www.weeklyosm.eu/archives/{c.url_nr}

  Enjoy! 

  Did you know that you can also submit messages for the weeklyOSM? Just log in to https://osmbc.openstreetmap.de/login with your OSM account. Read more about how to write a post here: https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm 

  weeklyOSM? 
  who: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
  where?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
